### PR TITLE
Negative feature

### PR DESCRIPTION
**Pull request by ChanRathke**

### CODE REVIEW

**Review by hergin — CHANGES_REQUESTED** [review]
The name of the test folder should be `test`.

**Comment by ChanRathke** [comment]
> The name of the test folder should be `test`.

Folder has been renamed

**Comment by hergin** [comment]
Why there is not github actions file in the branch? Probably you created branch after you created the actions file. Anyway, tests should pass. You have to merge this pull request somehow. Are tests passing in the codespaces?

**Review by hergin — APPROVED** [review]

**Review by Lukas-Maynard — APPROVED** [review]
yuh

**Comment by ChanRathke** [comment]
yuh x2

**Pull request merged**
